version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: docugen-nginx
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/var/www/html"
    ports:
      - "8000:80"
    depends_on:
      - php
  php:
    build: 
      context: src 
    container_name: docugen-php
    volumes:
      - "./src:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"